FROM python:3.13-slim
WORKDIR /app
COPY shared/ ./shared/
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY authentication_service/ ./authentication_service/
COPY migrations/ ./migrations/
COPY alembic.ini .
ENV PYTHONPATH=/app
CMD ["uvicorn", "authentication_service.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
