"""remove album and cover_url from songs

Revision ID: 42abf61683d0
Revises: 8895218d5c7d
Create Date: 2026-06-30 20:53:16.035452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42abf61683d0'
down_revision: Union[str, Sequence[str], None] = '8895218d5c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('songs_spotify_track_id_key'), 'songs', type_='unique')
    op.create_index(op.f('ix_songs_spotify_track_id'), 'songs', ['spotify_track_id'], unique=True)
    op.drop_column('songs', 'album')
    op.drop_column('songs', 'cover_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('cover_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('songs', sa.Column('album', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_songs_spotify_track_id'), table_name='songs')
    op.create_unique_constraint(op.f('songs_spotify_track_id_key'), 'songs', ['spotify_track_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
